const actionsType = {
    LOGIN_PROGRESS: 'LOGIN_PROGRESS',
    LOGIN_SUCCEED: 'LOGIN_SUCCEED',
    LOGIN_FAIL: 'LOGIN_FAIL',

    SIGNUP_PROGRESS: 'SIGNUP_PROGRESS',
    SIGNUP_SUCCEED: 'SIGNUP_SUCCEED',
    SIGNUP_FIAL: 'SIGNUP_FAIL',

    SIGNOUT_PROGRESS: 'SIGNOUT_PROGRESS',
    SIGNOUT_SUCCEED: 'SIGNOUT_SUCCEED',
    SIGNOUT_FAIL: 'SIGNOUT_FAIL',

    MAKE_ISERROR_FALSE: "MAKE_ISERROR_FALSE",

    HOME_FLAG: "HOME_FLAG",

    UPDATE_NAVBAR: "UPDATE_NAVBAR",

    GET_BUSROUTE_PROGRESS: 'GET_BUSROUTES_PROGRESS',
    GET_BUSROUTE_SUCCEED: 'GET_BUSROUTE_SUCCEED',
    GET_BUSROUTES_FAIL: 'GET_BUSROUTE_FAIL',

    GET_BUSINFO_PROGRESS: "GET_BUSINFO_PROGRESS",
    GET_BUSINFO_SUCCEED: "GET_BUSINFO_SUCCEED",
    GET_BUSINFO_FAIL: "GET_BUSINFO_FAIL",


    GET_ETAINFO_PROGRESS: "GET_ETAINFO_PROGRESS",
    GET_ETAINFO_SUCCEED: "GET_ETAINFO_SUCCEED",
    GET_ETAINFO_FAIL: "GET_ETAINFO_FAIL"
};

export default actionsType;