const actionsType = {
    LOGIN_PROGRESS: 'LOGIN_PROGRESS',
    LOGIN_SUCCEED: 'LOGIN_SUCCEED',
    LOGIN_FAIL: 'LOGIN_FAIL',

    SIGNUP_PROGRESS: 'SIGNUP_PROGRESS',
    SIGNUP_SUCCEED: 'SIGNUP_SUCCEED',
    SIGNUP_FIAL: 'SIGNUP_FAIL',

    SIGNOUT_PROGRESS: 'SIGNOUT_PROGRESS',
    SIGNOUT_SUCCEED: 'SIGNOUT_SUCCEED',
    SIGNOUT_FAIL: 'SIGNOUT_FAIL',

    GET_ALL_BUSES_PROGRESS: 'GET_ALL_BUSES_PROGRESS',
    GET_ALL_BUSES_SUCCEED: 'GET_ALL_BUSES_SUCCEED',
    GET_ALL_BUSES_FAIL: 'GET_ALL_BUSES_FAIL',

    SET_EDIT_OBJ: 'SET_EDIT_OBJ',
    INFO_UPDATE_OBJ: 'INFO_UPDATE_OBJ',

    CHANGE_PASSWORD_PROGRESS: "CHANGE_PASSWORD_PROGRESS",
    CHANGE_PASSWORD_SUCCEED: "CHANGE_PASSWORD_SUCCEED",
    CHANGE_PASSWORD_FAIL: "CHANGE_PASSWORD_FAIL",

    SET_ADMIN_FLAG: "SET_ADMIN_FLAG",

    RESET_ADMIN_FLAG: "RESET_ADMIN_FLAG",

    MAKE_ISERROR_FALSE: "MAKE_ISERROR_FALSE",

    HOME_FLAG: "HOME_FLAG",

    UPDATE_NAVBAR: "UPDATE_NAVBAR",

    SUBSCRIBE_TO_TOPIC: 'SUBSCRIBE_TO_TOPIC',

    GET_BUSROUTE_PROGRESS: 'GET_BUSROUTES_PROGRESS',
    GET_BUSROUTE_SUCCEED: 'GET_BUSROUTE_SUCCEED',
    GET_BUSROUTES_FAIL: 'GET_BUSROUTE_FAIL',

    GET_BUSINFO_PROGRESS: "GET_BUSINFO_PROGRESS",
    GET_BUSINFO_SUCCEED: "GET_BUSINFO_SUCCEED",
    GET_BUSINFO_FAIL: "GET_BUSINFO_FAIL",


    GET_ETAINFO_PROGRESS: "GET_ETAINFO_PROGRESS",
    GET_ETAINFO_SUCCEED: "GET_ETAINFO_SUCCEED",
    GET_ETAINFO_FAIL: "GET_ETAINFO_FAIL",


    ADD_ROUTE_PROGRESS: 'ADD_ROUTE_PROGRESS',
    ADD_ROUTE_SUCCEED: 'ADD_ROUTE_SUCCEED',
    ADD_ROUTE_FAIL: 'ADD_ROUTE_FAIL',

    UPDATE_ROUTE_PROGRESS: 'UPDATE_ROUTE_PROGRESS',
    UPDATE_ROUTE_SUCCEED: 'UPDATE_ROUTE_SUCCEED',
    UPDATE_ROUTE_FAIL: 'UPDATE_ROUTE_FAIL',


    UPDATE_BUS_INFO_PROGRESS: 'UPDATE_BUS_INFO_PROGRESS',
    UPDATE_BUS_INFO_SUCCEED: 'UPDATE_BUS_INFO_SUCCEED',
    UPDATE_BUS_INFO_FAIL: 'UPDATE_BUS_INFO_FAIL',


    ADD_BUSINFO_PROGRESS: 'ADD_BUSINFO_PROGRESS',
    ADD_BUSINFO_SUCCEED: 'ADD_BUSINFO_SUCCEED',
    ADD_BUSINFO_FAIL: 'ADD_BUSINFO_FAIL',

    DELETE_ROUTE_PROGRESS: 'DELETE_ROUTE_PROGRESS',
    DELETE_ROUTE_SUCCEED: 'DELETE_ROUTE_SUCCEED',
    DELETE_ROUTE_FAIL: 'DELETE_ROUTE_FAIL',

    DELETE_INFO_PROGRESS: 'DELETE_INFO_PROGRESS',
    DELETE_INFO_SUCCEED: 'DELETE_INFO_SUCCEED',
    DELETE_INFO_FAIL: 'DELETE_INFO_FAIL'

};

export default actionsType;